### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by Lathrisk** [ThreeSixtyGiving/registry#75] opened 2021-06-15 16:07 UTC
Publisher filters are under full review and possible redesign.

**Comment by codemacabre** [comment] 2023-05-11 18:22
@mariongalley Michael raised the very good point that in its current (unreleased) implementation, the new badge filter will display publishers with _any one_ of the selected badges (i.e. an OR), but you may want it to only select publishers with _all_ of the selected badges (i.e. an AND).

OR:
![image](https://github.com/ThreeSixtyGiving/registry/assets/49149591/a2f5ac72-30d7-46e6-afc8-403cadee61a5)

AND:
![image](https://github.com/ThreeSixtyGiving/registry/assets/49149591/0817d996-8ea9-48bd-83db-34dc5da17897)


If that makes sense, please could you let me know which implementation of the filter you'd prefer?

**Comment by mariongalley** [comment] 2023-05-15 08:47
@codemacabre I think the AND logic would be preferable for this use-case.

Also can I check whether there's currently a way to filter either positively or negatively i.e. 'does share Programme name' but also 'does not share Programme name'?

**Comment by codemacabre** [comment] 2023-05-16 13:18
> @codemacabre I think the AND logic would be preferable for this use-case.
Thank you @mariongalley I'll get on that.

> Also can I check whether there's currently a way to filter either positively or negatively i.e. 'does share Programme name' but also 'does not share Programme name'?
Not currently, but implementing it might involve some design decisions a little beyond the scope of this initial work. What do you envision the UI looking like?

**Comment by codemacabre** [comment] 2023-05-23 08:32
@mariongalley Does this sound like a decent plan?

1. Set filters to work with AND rather than OR
2. Add the filters sidebar to the dashboard (similar to GrantNav)
3. Move the Select Publishers and Select Badges filters to the sidebar (keeping the sort at the top of the search results)
4. Allow including and excluding filter functionality (as in GrantNav)

Very crude mockup: 
![image 1](https://github.com/ThreeSixtyGiving/registry/assets/49149591/6c20e44f-6b04-4881-b786-3c63e0ede037)

**Comment by mariongalley** [comment] 2023-05-23 08:48
@codemacabre Is the reason for moving the filters to the left that there would now be essentially one picker for each quality feature rather than a shared picker for all of them?

Yes, what you've described is exactly right thank you

**Comment by codemacabre** [comment] 2023-05-23 09:05
@mariongalley I was thinking it would just make the design and flow more consistent across applications rather than split each feature into its own filter, but that might be a bit busy compared to the shared picker.

**Comment by mariongalley** [comment] 2023-05-23 09:09
@codemacabre That makes sense - no go ahead and do what you had in mind!

**Comment by codemacabre** [comment] 2023-05-25 08:22
@mariongalley Just working on this and noticed some odd behaviour with the publisher filter and new badge filter (the AND version not yet live). It seems the publisher filter uses OR, so when combined with badge filters, the results are quite unexpected.

There are definitely a couple of bugs to iron out, but I wondered if there is a use case for combining the publisher filters with badge filters, and if so, how it should work? Or should changing the badges filter automatically clear the publisher filter?

**Comment by mariongalley** [comment] 2023-05-25 10:47
@codemacabre Ideally we would like to be able to filter by data quality feature for a group of selected publishers. Do you mean that it is showing unexpected results because there are sometimes no relevant publishers to return, or is it that you're unable to set up a query that correctly returns any of the selected publishers that have all (or none, if exclude) of the selected features?

**Comment by mariongalley** [comment] 2023-06-01 09:37
Thanks for this @codemacabre - would it be possible to limit the maximum width of the contents of the tabs, like in the live dashboard?

At the moment on the All Data tab, the tab switching feels really lonely all the way off to the left of the screen, and on the Publishers tab the Heatmap looks really wide and is harder to read as a result.

All Data - live
![image](https://github.com/ThreeSixtyGiving/registry/assets/82958988/be29aa50-acbc-4af9-9710-9b3d26faa3b3)

All Data - dev
![image](https://github.com/ThreeSixtyGiving/registry/assets/82958988/26cce76f-4214-40bb-b7a8-bd9f009bc78f)

Publishers tab - live
![image](https://github.com/ThreeSixtyGiving/registry/assets/82958988/8ccf0684-1e6e-493a-b8f1-456a3ba7515e)

Publishers tab - dev
![image](https://github.com/ThreeSixtyGiving/registry/assets/82958988/e4c37a38-da73-48d6-a0d0-2d6751f19ea7)

With the addition of the filters I think it makes sense for them to sit in the left margin outside of the main content 'pane' (not sure the right word for this)

**Comment by mariongalley** [comment] 2023-06-01 09:42
In terms of the functioning of the filter, so far they all behave as expected except the two duration features, which return no results despite many publishers having those badges

**Comment by mariongalley** [comment] 2023-06-16 09:25
@codemacabre I've retested and these all work as expected now. The only blocker to launch is the additional information area which doesn't quite look right to me.

**Comment by codemacabre** [comment] 2023-06-20 07:02
> The only blocker to launch is the additional information area which doesn't quite look right to me.

@mariongalley Is the issue that the overall placement? The layout is an exact duplicate of the one currently on the registry, but the width looks a bit odd to me. Perhaps it needs to be wider? Or a smaller font size?

**Comment by mariongalley** [comment] 2023-06-20 08:31
@codemacabre It's not so much the layout as the fact the font weight etc didn't match the rest of the Quality Dashboard. However, I commented on [#122](https://github.com/ThreeSixtyGiving/registry/issues/122#issuecomment-1594414864) that I think we can reproduce the functionality while getting rid of the explainer copy.

**Comment by codemacabre** [comment] 2023-06-22 05:21
Deployed to live!

**Closed by codemacabre** 2023-06-22 05:21 UTC
Labels: dashboard, Prerequisite for Registry depreciation
